# site
title: Brandon Nguyen
baseurl: ""
url: ""

# bio
header: Brandon Nguyen
desc: >
    I'm a second-year computer science student at San Diego State University. 
    <br> 
contact: >
    gnuyent (at) protonmail (dot) com

# posts
date_format: "%B %d, %Y"
post_title: Post
post_date: Date
post_cat: Category

# post detail
prev-next: true

# build settings
markdown: kramdown
theme: louie
exclude:
  - Gemfile
  - Gemfile.lock
