# site
title: gnuyent
baseurl: ""
url: ""
favicon: "/assets/favicon.ico"

# bio
header: Brandon Nguyen
desc: >
  Computer Science Freshman at San Diego State University.

# posts
date_format: "%m/%d/%Y"
post_title: Post
post_date: Date
post_cat: Category

# post detail
prev-next: false

# build settings
markdown: kramdown
theme: louie
exclude:
  - Gemfile
  - Gemfile.lock