baseurl      = "https://gnuyent.dev"
title        = "gnuyent"
languageCode = "en-us"
theme        = "cactus"
copyright = "gnuyent"
publishDir   = "docs/"

# Metadata mostly used in document's head
description = "gnuyent"
keywords = "homepage, blog"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Posts"
  url = "/posts"
  weight = 2

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[params]
  description = "Hi! My name is Brandon. I'm a third-year Computer Science student at SDSU and Software Engineer Intern at Intuit."
  mainSection = "posts"
  mathjax = true
  postsOnHomePage = 5
  rss = true
  showProjectsList = true
  projectsUrl = "https://github.com/gnuyent"
  showReadTime = true
  show_updated = true

  [[params.social]]
    name = "email"
    link = "gnuyent@protonmail.com"

  [[params.social]]
    name = "github"
    link = "https://github.com/gnuyent"

  [[params.social]]
    name = "linkedin"
    link = "https://linkedin.com/in/brandonnguyen02"

